const ROOM_NOT_FOUND_ERROR = 'SLERR_ROOM_NOT_FOUND';
const ROOM_MAX_USER_ERROR = 'SLERR_ROOM_MAX_USER';
const ROOM_MAX_ERROR = 'SLERR_ROOM_MAX';

module.exports = {
    ROOM_NOT_FOUND_ERROR, ROOM_MAX_USER_ERROR, ROOM_MAX_ERROR
}